version: '3.6'
services:
  #
  # Shard 1 replica set
  #
  mongors1n1:
    container_name: mongors1n1
    image: mongo:latest
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    #restart: always
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data1:/data/db
  mongors1n2:
    container_name: mongors1n2
    image: mongo:latest
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    #restart: always
    ports:
      - 27027:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data2:/data/db
  mongors1n3:
    container_name: mongors1n3
    image: mongo:latest
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    #restart: always
    ports:
      - 27037:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mogno_cluster/data3:/data/db


  #
  # Shard 2 replica set
  #
  mongors2n1:
    container_name: mongors2n1
    image: mongo:latest
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    #restart: always
    ports:
      - 27047:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data4:/data/db
  mongors2n2:
    container_name: mongors2n2
    image: mongo:latest
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    #restart: always
    ports:
      - 27057:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data5:/data/db
  mongors2n3:
    container_name: mongors2n3
    image: mongo:latest
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    #restart: always
    ports:
      - 27067:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/data6:/data/db

  #
  # Config services (metadata services )
  #

  mongocfg1:
    container_name: mongocfg1
    image: mongo:latest
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config1:/data/db
  mongocfg2:
    container_name: mongocfg2
    image: mongo:latest
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config2:/data/db
  mongocfg3:
    container_name: mongocfg3
    image: mongo:latest
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config3:/data/db

  #
  # Mongos instances (routers )
  #

  mongos1:
    container_name: mongos1
    image: mongo:latest
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mongos2:
    container_name: mongos2
    image: mongo:latest
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro