version: "3"
services:
  mongo_rs1_n1:
    container_name: c_mongo_rs1_n1
    image: mongo:5.0.3
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017 --bind_ip_all
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR/data1:/data/db
    networks:
      - streetmap_network

  mongo_rs1_n2:
    container_name: c_mongo_rs1_n2
    image: mongo:5.0.3
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017 --bind_ip_all
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR/data2:/data/db
    networks:
      - streetmap_network

  mongo_rs1_n3:
    container_name: c_mongo_rs1_n3
    image: mongo:5.0.3
    command: mongod --shardsvr --replSet mongo_rs1 --dbpath /data/db --port 27017 --bind_ip_all
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR/data3:/data/db
    networks:
      - streetmap_network

networks:
  streetmap_network:
    external: true
    name: map_net