version: "2"
services:
  mongo_rs2_n1:
    container_name: c_mongo_rs2_n1
    image: mongo:5.0.3
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 27047:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR/data4:/data/db
    networks:
      - streetmap_network

  mongo_rs2_n2:
    container_name: c_mongo_rs2_n2
    image: mongo:5.0.3
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 27057:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR/data5:/data/db
    networks:
      - streetmap_network

  mongo_rs2_n3:
    container_name: c_mongo_rs2_n3
    image: mongo:5.0.3
    command: mongod --shardsvr --replSet mongo_rs2 --dbpath /data/db --port 27017
    ports:
      - 27067:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR/data6:/data/db
    networks:
      - streetmap_network

networks:
  streetmap_network:
    external: true
    name: map_net